Updates on Caja
fuegoaustral/ticketera pull request #39
Opened 2024-10-20 21:14 UTC by guillermodoghel

Emision directa de bonos | CAJA - 
Opciones: Pago en efectivo / Bonos internacionales / Transferencia
Agregar un campo notas
Logear quien cobra

Fix
En la CAJA: si ponés un email de usuario, después ponés verificar, después cambiás el email a un usuario inexistente y hacés enter se submitea el form en vez de correr la verificación y queda con el usuario original pero con el emai de usuario que no existe

2024-10-21 01:41 UTC, vfonic requested changes
Los

```html
                                    <option value="ART">Pago Internacional</option>
                                    <option value="CAMPS">Transferencia nacional</option>
```

me parecen importantes para cambiar.

2024-10-21 01:41 UTC, vfonic commented on tickets/templates/admin/admin_caja.html
> +                                    <option value="CAMPS">Transferencia nacional</option>
Acá y arriba dejaste el viejo atributo `value`.

2024-10-21 01:41 UTC, vfonic commented on tickets/templates/admin/base_site.html
> +        <li><a href="{% url 'admin_caja_view' %}">{% trans 'EMISION DIRECTA DE BONOS - EFECTIVO / TRANSFERENCIAS' %}</a>
No sé si necesitamos utilizar `trans`. Hay pruebas de que alguien está usando la `ticketera` fuera de nosotros? Y la usa en otro idioma? Si no... por qué no nos hacemos las vidas más fáciles y no usamos `trans`?

2024-10-21 03:02 UTC, guillermodoghel commented on tickets/templates/admin/base_site.html
> +        <li><a href="{% url 'admin_caja_view' %}">{% trans 'EMISION DIRECTA DE BONOS - EFECTIVO / TRANSFERENCIAS' %}</a>
makes sense

2024-10-21 03:02 UTC, guillermodoghel commented on tickets/templates/admin/admin_caja.html
> +                                    <option value="CAMPS">Transferencia nacional</option>
good catch!

2024-10-21 03:24 UTC, vfonic approved these changes
LGTM! :shipit:

2024-10-21 12:05 UTC, rasca requested changes
Apruebo mergear pero vamos a tener que hacer algunos cambios por sobre esto:

El participante carga su propio email por duplicado en otro "paso" con el resumen.

Mergeemos este PR y lo hacemos luego.

2024-10-21 12:05 UTC, rasca commented on tickets/admin.py
> +                    notes = "Operador responsable: " + request.user.email + ' - ' + form.cleaned_data['notes']
Esto lo haría con un ForeignKey a User

2024-10-21 12:05 UTC, rasca commented on tickets/forms.py
>      (Order.OrderType.CASH_ONSITE, 'Pago en efectivo en el evento'),
Cambiaría "en el evento" por "en persona". Porque no va a haber evento en la venta dirigida como si lo es en un evento de la sede.

2024-10-21 12:05 UTC, rasca commented on tickets/templates/admin/admin_caja.html
>                                      <option value="CASH_ONSITE">Compra en efectivo</option>
Todo esto se puede sacar del `OrderType` directamente. No hace falta "harcodearlo"

2024-10-22 14:50 UTC, guillermodoghel commented on tickets/templates/admin/admin_caja.html
>                                      <option value="CASH_ONSITE">Compra en efectivo</option>
Ojo que no son TODAS las opcciones

2024-10-22 16:47 UTC, rasca approved these changes

2024-10-22 17:33 UTC, merged