Admin bonos dirigidos
fuegoaustral/ticketera pull request #40
Opened 2024-10-21 02:49 UTC by guillermodoghel

DirectTicketTemplate vendria a ser una row del excel

![Screenshot 2024-10-20 at 11 45 27 PM](https://github.com/user-attachments/assets/4f309c04-1518-4137-a35a-2943805360c1)
![Screenshot 2024-10-20 at 11 45 16 PM](https://github.com/user-attachments/assets/33466147-3969-472e-93f6-4c8e9a0f91e5)

Y luego un operador los asigna desde aca
![Screenshot 2024-10-20 at 11 44 53 PM](https://github.com/user-attachments/assets/fae168fa-bbcb-4c29-8351-dd26f8d1fbd7)

2024-10-21 11:57 UTC, rasca commented
Cambiar `origin` por un checkbox

2024-10-21 11:59 UTC, rasca commented
- Cambiar origin por un checkbox
- El operador que sea el usuario logueado en ese momento
- El operador carga el nombre de la persona que compra, pero para uso interno
- El participante comprador carga su email por duplicado en un paso con el resumen de la compra
- Ok con importar el excel a mano, sino que alguien lo cargue con tiempo, es lo mismo

2024-10-28 15:34 UTC, vfonic requested changes
Me parece que deberíamos remover `used` y `status` del formulario acá: http://127.0.0.1:8000/admin/tickets/directtickettemplate/add/
?

2024-10-29 03:03 UTC, guillermodoghel commented on utils/direct_sales.py
> +                    if not user_already_has_ticket and first_ticket:
nice catch!

2024-10-29 03:13 UTC, guillermodoghel commented on tickets/migrations/0039_alter_directtickettemplate_options_and_more.py
> +            name='used',
es verdad, es redudante, used == not AVAILABLE

2024-10-29 03:18 UTC, merged

2024-10-29 10:48 UTC, rasca commented
🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥