Select tickets page updates
fuegoaustral/ticketera pull request #48
Opened 2024-10-26 00:21 UTC by vfonic

2024-10-26 00:26 UTC, vfonic commented on tickets/forms.py
> +            ]
Esto permite mostrar el error de validación pero manteniendo las cantidades que agregó el usuario en el formulario en lugar de mostrar el formulario vacío.

2024-10-26 00:26 UTC, vfonic commented on tickets/templates/checkout/select_tickets.html
> -                            ticketsRemainingByType[ticketId] -= increment;
Esto era un error de "off by one" donde si había 2 entradas disponibles solo podías seleccionar 1.

2024-10-26 00:26 UTC, vfonic commented on tickets/templates/checkout/select_tickets.html
> +                    document.getElementById('subtotal').innerText = '$' + subtotal.toLocaleString('es-AR', { minimumFractionDigits: 0, maximumFractionDigits: 2 });
Mantiene el formato consistente con `Format prices` PR #47

2024-10-26 00:26 UTC, vfonic commented on tickets/templates/tickets/home.html
> +                            href="{% url 'select_tickets' %}?new&ticket_id={{ ticket_type.id }}"
Permite agregar cantidad 1 para este ticket en la próxima página.

2024-10-26 00:26 UTC, vfonic commented on tickets/views/checkout.py
> +            available_tickets = min(available_tickets, tickets_remaining)
Prefiero duplicar este código a mezclar GET y POST. Mezclar estas funcionalidades tan diferentes puede llevar fácilmente a errores.

2024-10-26 00:31 UTC, guillermodoghel commented on tickets/templates/checkout/select_tickets.html
> +                        </style>
yolo

2024-10-26 02:36 UTC, vfonic commented on tickets/templates/checkout/select_tickets.html
> +                        </style>
Desde hace muchos años escribo muchas veces CSS en `<style>`. Es mejor de escribir en `style=` atributo porque podés agregar estilos para `:hover`, `@media` queries...
Y, cuando remueves HTML, podés inmediatamente remover el CSS también.

2024-10-27 13:57 UTC, rasca requested changes

2024-10-27 13:57 UTC, rasca commented on tickets/templates/checkout/select_tickets.html
Se rompió el JS que no te deja seleccionar más tickets de los permitidos por compra.
<img width="933" alt="Screenshot 2024-10-27 at 10 50 16" src="https://github.com/user-attachments/assets/368dbd38-6fd6-4bd5-b71d-686fcc6fd9d2">

2024-10-27 13:57 UTC, rasca commented on tickets/templates/checkout/select_tickets.html
Ahora aparece el popup pero el input sigue creciendo

2024-10-27 13:57 UTC, rasca commented on tickets/forms.py
> +            raise ValidationError(f'No hay suficientes bonos disponibles. Quedan {available_tickets} bonos.')
Cambiaría el copy.


A veces se llegar a este error porque no hay más bonos disponibles, a veces porque se llegó al limite de bonos por compra.

f'Superaste la máxima cantidad de bonos dispoibles para esta compra: {available_tickets}.'

2024-10-27 20:08 UTC, vfonic commented on tickets/templates/checkout/select_tickets.html
Sí, porque el input sigue cambiando (bajando y/o creciendo). Eso es necesario porque ahora podés escribir cualquier número dentro de la caja. Si escribís 3 en ambas cajitas y querés bajar la cantidad, no podés porque el viejo código no te deja bajar (cambiar) la cantidad.

2024-10-27 20:14 UTC, vfonic commented on tickets/forms.py
> +            raise ValidationError(f'No hay suficientes bonos disponibles. Quedan {available_tickets} bonos.')
> No hay suficientes bonos disponibles. Quedan 0 bonos.

vs

> Superaste la máxima cantidad de bonos disponibles para esta compra: 0.

No me suenan ni uno ni otro mensaje. Haré este cambio ahora, pero me parece que deberíamos cambiar el mensaje para que sea más claro.

2024-10-28 02:17 UTC, rasca approved these changes

2024-10-28 12:23 UTC, merged