Select donations page updates
fuegoaustral/ticketera pull request #49
Opened 2024-10-26 16:45 UTC by vfonic

2024-10-26 23:56 UTC, guillermodoghel commented
Reemplazaria los botones individuales de monto con un selector de opciones. Podrías usar un dropdown para los montos predefinidos y un campo de texto para el monto seleccionado, lo que reduciría la cantidad de botones y haría la interfaz un poco más limpia (mas que nada en mobile)

Agregaria una opción como "Otra cantidad" o "Monto personalizado" al final del dropdown. Al seleccionarla, el campo de texto para el monto personalizado se activaría.

2024-10-27 14:11 UTC, rasca commented
> Reemplazaria los botones individuales de monto con un selector de opciones. Podrías usar un dropdown para los montos predefinidos y un campo de texto para el monto seleccionado, lo que reduciría la cantidad de botones y haría la interfaz un poco más limpia (mas que nada en mobile)
> 
> Agregaria una opción como "Otra cantidad" o "Monto personalizado" al final del dropdown. Al seleccionarla, el campo de texto para el monto personalizado se activaría.

me parece bien para más adelante, por ahora vamos con esto!

2024-10-27 14:11 UTC, rasca requested changes

2024-10-27 14:11 UTC, rasca commented on tickets/templates/checkout/select_donations.html
> +                        font-weight: 400;
está desalineado el $, cambiar css por:

```
  line-height: 1.5rem;
  padding: calc(0.375rem + 1px) 0;
  margin-left: .25rem;

```
Before:
<img width="162" alt="Screenshot 2024-10-27 at 11 07 28" src="https://github.com/user-attachments/assets/e3aae368-97c3-4b02-8856-7e71859c5e2b">


After:
<img width="172" alt="Screenshot 2024-10-27 at 11 08 18" src="https://github.com/user-attachments/assets/ca0d50b8-6da1-4925-b11c-28ec68cf05d9">

2024-10-27 14:11 UTC, rasca commented on tickets/templates/checkout/select_donations.html
> +                                                onclick="setDonationAmount('art', 5000)">$5.000
Me gusta como lo resolviste. Ahora lo mergearía así y más adelante haría que se pueda modificar desde el backend en el Evento.

Por otro lado, lo montos los vamos a necestar cambiar pero podemos cambiar el hardcoded value cuando hable con el equipo de fundraising.

2024-10-27 20:47 UTC, vfonic commented on tickets/templates/checkout/select_donations.html
> +                        font-weight: 400;
Qué navegador usás?

2024-10-27 20:49 UTC, vfonic commented on tickets/templates/checkout/select_donations.html
> +                        font-weight: 400;
Puede ser que tenés una extensión que te cambia el input field?

2024-10-28 02:18 UTC, rasca approved these changes

2024-10-28 02:18 UTC, rasca commented on tickets/templates/checkout/select_donations.html
> +                        font-weight: 400;
Firefox, sin nada raro

2024-10-28 12:23 UTC, merged